targets:
  $default:
    builders:
      # dosty_theme_generator|dosty_theme_annotation:
      generators|annotations:
        enabled: true

builders:
  generators:
    target: ":dosty_theme_generator"
    import: "package:dosty_theme_generator/dosty_theme_generator.dart"
    builder_factories: ["dostyThemeGenerate"] # Builder name(BuilderOption) this is a definition
    build_extensions: { ".dart": [".g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]